### ISSUE TITLE
Additive configuration is problematic - suggest overriding instead

### ISSUE THREAD

**Issue by seddy** [reevoo/sapience-rb#21]
In [reevoo-sapience](https://github.com/reevoo/reevoo_sapience-rb), we have the following configuration:

```yaml
default:
  log_level: debug
  appenders:
    - datadog:
        url: <%= ENV.fetch("STATSD_URL", "udp://localhost:8125") %>
    - stream:
        io: STDOUT
        formatter: json

development:
  log_level: debug
  appenders:
    - datadog:
        url: <%= ENV.fetch("STATSD_URL", "udp://localhost:8125") %>
    - stream:
        io: STDOUT
        formatter: color
    - stream:
        file_name: log/development.log
        formatter: color
```

The problem is that the stream configurations are additive.  So in the development environment we end up logging two `streams` to `STDOUT`: one using `color` and the other using `json`. This makes development very difficult to read and unnecessarily verbose.

I propose when we have a stream in `development` it overrides all `streams` from above it, to allow for greater flexibility in configuration.  Arguably the same should go for all appenders; I wonder whether we're logging twice to `datadog`?
